name = "testingGIT"
uuid = "ddc810ac-0837-4e88-97f5-55ffdeec0bfe"
authors = ["Veenty <vgh225@nyu.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
